### ISSUE TITLE
Update with other Grey Source games

### ISSUE THREAD

**Issue by sabianroberts** [thephoenixprojectsoftware/greysource#3]
- *Lost and Dead Classic*
- *Half-Life: Zombies Ate My Neighbours*

**Comment by reductor** [comment]
If the plan is to not do any further work on HL1, is there any need for the grey source stuff? Just seems like a bunch of unnecessary code to maintain.

**Comment by sabianroberts** [comment]
> If the plan is to not do any further work on HL1, is there any need for the grey source stuff? Just seems like a bunch of unnecessary code to maintain.

@ReDucTor Sorry for the late reply, I haven't been receiving E-Mails on my Outlook for some reason. You could try doing this issue (most of the changes are in phoenixprojectsoftware/zamnhl-sdk) and that might be Grey Source complete.

**Comment by reductor** [comment]
@barney-heatwave why is grey source necessary? zamnhl-sdk is already broken and lost its link between any files because of the moving of files being done without tracking details.

**Comment by sabianroberts** [comment]
@ReDucTor Grey Source was just something I started for fun in November 2019. If it seems significantly unnecessary I’ll stop work on it

**Comment by reductor** [comment]
@barney-heatwave ya it seems unnecessary, I know it's something that I don't want to be involved in maintaining.

**Comment by sabianroberts** [comment]
@ReDucTor No problem, I'll unassign you from this issue. I'll probably resolve this issue when I complete ZAMNHL in about November
